### ISSUE TITLE
Append to existing .xml

### ISSUE THREAD

**Issue by teemue** [tobinus/python-podgen#64]
Script is awesome. It's only lacking a function to open already existing file and appending new episodes.

**Comment by tobinus** [comment]
Yeah, that would be convenient. I don't really have much time to spare these days, but I might look at it sometime into 2018.

**Comment by tobinus** [comment]
Oh, a lot of time has passed since then. Looking at this with new eyes, I think that PodGen would be better off if it focused on generating RSS, and let the user of PodGen deal with getting the necessary information. So I'll close this as "out of scope". But nothing stops anyone from creating a separate library which parses an existing podcast and fills that information into PodGen's classes.
