### ISSUE TITLE
Support for special characters and links in podcast fields

### ISSUE THREAD

**Issue by strazeadin** [tobinus/python-podgen#70]
Hello, 

First of all, wanted to thank you for looking into updating this library! I've recently started using it for my own project and it's been working great.

I wanted to ask if you have a plan on how to handle encoding of fields such as description / author etc. to handle special characters and HTML. As an example, looking at the [RSS feed sample](https://help.apple.com/itc/podcasts_connect/#/itcbaf351599) provided by Apple you can see the description field using `&apos;` instead of `'` and also using `<content:encoded>` and `<![CDATA[]]>` wrapping when including a URL.

Do you have plans around supporting native proper encoding or still keeping it fairly simple and let users handle their own encoding / content wrapping needs? (I suppose the ability to extend the classes might simplify this as well in the future)

Keen to get your opinion on the matter.

**Comment by tobinus** [comment]
Thank you for reaching out!

Special characters are already encoded properly for all fields, I think. The only encoding that PodGen needs to do is to escape XML characters so that they are parsed as plain text and not XML markup by the RSS readers. For example, `<3` becomes `&lt;3`. Podcast applications expect plain text in almost all fields, so therefore if you try to put any HTML in e.g. the authors field, the podcast applications will not parse the HTML and instead just display it as-is.

The only exceptions to the above rule are [`Episode.summary`](https://podgen.readthedocs.io/en/latest/api.episode.html#podgen.Episode.summary) and [`Episode.long_summary`](https://podgen.readthedocs.io/en/latest/api.episode.html#podgen.Episode.long_summary), which expect HTML. So you should already be able to use links today when using the summary fields.

The implementation of those two fields, specifically the way they use `<description>` and `<content:encoded>`, is based on the RSS 2.0 specification and best practices at http://www.rssboard.org/rss-profile#namespace-elements-content-encoded . Podcast feeds are basically just RSS 2.0 with some additional tags defined by Apple, so I would be surprised if this does not work with Apple Podcasts.

That said, I have also noticed what you mention about Apple Podcasts recommending that you place `<content:encoded>` _inside_ of  `<description>`, which honestly sounds like a big misunderstanding at Apple. I first thought they had worded it poorly, but [their example](https://help.apple.com/itc/podcasts_connect/#/itcbaf351599) clearly uses it this way:

```xml
      <description>
        <content:encoded>
          <![CDATA[The Sunset Explorers share tips, techniques and recommendations for
          great hikes and adventures around the United States. Listen on 
          <a href="https://www.apple.com/itunes/podcasts/">Apple Podcasts</a>.]]>
        </content:encoded>
      </description>
```

The way I understand the RSS 2.0 specification, this is a mistake. I have never seen anyone use `<content:encoded>` this way, and all resources I find on the internet describe it as being a _sibling_ of `<description>`, not a descendant. So I have chosen to adapt the more widely used interpretation of those elements, specifically to use `<description>` when only one summary is available, and use `<content:encoded>` for the long summary when both are provided. Both are placed underneath `<item>`.

If this turns out to be incompatible with Apple Podcasts when actually submitting the feed or viewing it in their podcast directory, then I would like to try to fix that in a way that works for most podcast applications. Please create an issue or update this one if you encounter an incompatibility like that :)

Somewhat related, I have been thinking about how there seems to not be very much support for having both a short summary and a full summary, so there is a chance that I will be retiring `Episode.long_summary` in a future release. But not before I have researched some more about how well supported it is.

**Comment by strazeadin** [comment]
Thank you so much for your very detailed response, I clearly understand your point on this and it's good to know that encoding is already handled. I wasn't aware that `Episode.summary` and `Episode.long_summary` expect HTML and that's good know.

I think my confusion came from following the [Full Example - PodGen Docs](https://podgen.readthedocs.io/en/latest/usage_guide/example.html). It uses `htmlencode` on the summary field which resulted with things like `"` turning into `&quot;` and it wasn't being encoded back properly by Apple/iTunes. I might have got confused as well looking at some other libraries that have more explicit encoding rules (such as [feedparser](https://github.com/kurtmckee/feedparser/blob/develop/feedparser/parsers/loose.py))

Happy to close this issue off for now. Keep up the good work!
